export const PLACE_TYPES = [
  'House',
  'Shop',
  'Office',
  'School',
  'Hospital',
  'Estate Gate',
  'Warehouse',
  'Hotel',
  'Police Station',
  'Church',
  'Mosque',
  'Barracks',
  'Public Building',
  'Government Office',
  'Market',
  'Other',
];